### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by vic014** [thijsbekke/Octoprint-LaMetric#1]
trying to get API Key
the following message pop's -up 

Connect your Octoprint with LaMetric
Something is gone wrong, if you are curtain this is not your fault, please create an issue at https://github.com/thijsbekke/OctoPrint-LaMetric

**Comment by thijsbekke** [comment]
Damn, I do not log any data and that makes it hard too know what is going on. I will dive into it. You hear from me.

**Comment by Sidewalkhorse** [comment]
same here! also what is the host?

**Comment by thijsbekke** [comment]
Host is the host / ip adress of your LaMetric Time, when you log in it supposed to give it back to you. Unfortunately, I don't know why.

I am working on an update where it gives you more info what is wrong.

**Comment by thijsbekke** [comment]
On the error page it displays more information what is going wrong. Can you please try it again and when it fails, paste the error here? 

Please review it for any personal data.

**Comment by thijsbekke** [comment]
After enabling the logging for quite some time, I don't see any errors. Can I assume it is fixed?
