### ISSUE TITLE
Endless Update

### ISSUE THREAD

**Issue by DunklerPhoenix** [thijsbekke/Octoprint-LaMetric#2]
Heho. 
Your plugin got a little updateloop :D 
`Successfully built OctoPrint-LaMetric
Looks like we were already installed in this version. Forcing a reinstall.
/home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install https://github.com/thijsbekke/OctoPrint-LaMetric/archive/0.1.2.zip --no-cache-dir --ignore-installed --force-reinstall --no-deps
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/thijsbekke/OctoPrint-LaMetric/archive/0.1.2.zip
Downloading https://github.com/thijsbekke/OctoPrint-LaMetric/archive/0.1.2.zip
Building wheels for collected packages: OctoPrint-LaMetric
Building wheel for OctoPrint-LaMetric (setup.py): started
Building wheel for OctoPrint-LaMetric (setup.py): finished with status 'done'
Created wheel for OctoPrint-LaMetric: filename=OctoPrint_LaMetric-0.1.1-cp27-none-any.whl size=18954 sha256=5f954d0e55769ffdca9cdf657f0276bbcbc19f30a282aaa31aa47a591df210d7
Stored in directory: /tmp/pip-ephem-wheel-cache-J4JSYT/wheels/c1/f8/62/c9c04843aff2cc4d18bfa8c022753f39749dc9a04b24208054
Successfully built OctoPrint-LaMetric
Installing collected packages: OctoPrint-LaMetric
Successfully installed OctoPrint-LaMetric-0.1.1
Die Aktualisierung wurde erfolgreich durchgeführt und der Server wird jetzt neu gestartet.`

**Comment by thijsbekke** [comment]
wow, uuh. I see it. for now I deleted this release that gives me some time to fix it. 

Thanks for mention it.

**Comment by thijsbekke** [comment]
@DunklerPhoenix with the latest release the issue is resolved. 

Thnx
