### ISSUE TITLE
API Key!!!

### ISSUE THREAD

**Issue by Sidewalkhorse** [thijsbekke/Octoprint-LaMetric#3]
Hello there. I really want this to work on my Lametric. But the obtain API Key doesnt work????

I just get this - 

Connect your Octoprint with LaMetric
Something is gone wrong, if you are curtain this is not your fault, please create an issue at https://github.com/thijsbekke/OctoPrint-LaMetric

**Comment by thijsbekke** [comment]
On the error page it displays more information what is going wrong. Can you please try it again and when it fails, paste the error here? 

Please review it for any personal data.

**Comment by thijsbekke** [comment]
After monitoring this for quite some time, I don't see any errors. Can I assume it is fixed?
