### ISSUE TITLE
Sending failed: Only notifications with priority 'critical' are allowed in current mode

### ISSUE THREAD

**Issue by lennvilardi** [thijsbekke/Octoprint-LaMetric#4]
Hi !
Since I upgraded Octoprint to 1.4.1. I've got this message error from the settings panel of the plugin when pressed test : Sending failed: Only notifications with priority 'critical' are allowed in current mode.
Any idea ?
Thanks for all

**Comment by thijsbekke** [comment]
Yes, is it dark in your room? 😛

LaMetric time has an screensaver function which is default enabled when it is dark. When the screensaver is enabled you only can send ciritical notifications.

**Comment by lennvilardi** [comment]
ahah you're totally right I'm such a fool !
The shutter was closed to prevent heat.
