### ISSUE TITLE
Not found error

### ISSUE THREAD

**Issue by jmarc67** [thijsbekke/Octoprint-LaMetric#5]
Hello,

I installed your plugin and the Octoprint plugin in my LaMetric.
All is ok in octoprint, Api key and Host (Test OK, sent successfully)

But i can see only "**X Not Found**" on my La Metric Screen.

Is there something more to do to work ?

Thanks for your help.

**Comment by thijsbekke** [comment]
Hi, 

It are two different apps/plugins with different purposes. 

The purpose of the OctoPrint app on your LaMetric is too display the number of installs of a plugin.  In the settings of this app (in the LaMetric app) you can enter your a OctoPrint plugin name. If none is entered "X Not Found" is displayed (maybe that is a bit confusing ..) 

Too display the progress of a print printed with OctoPrint no app on your LaMetric is required. 

Hope this helps


Below a screenshot of the settings in de LaMetric app.
![Screenshot](https://user-images.githubusercontent.com/1152678/101793551-3762da80-3b06-11eb-9248-0957900b9b0d.png)

**Comment by jmarc67** [comment]
Oh my god, i'm so stupid...
You're right.
No app on LaMetric is required to see my print

Thanks for all, your plugin is great

**Comment by jmarc67** [comment]
Hello,

 

One more thing , i can see 

Support for multiple devices

I’ll buy one more Lametric. I need this.

Can you tell me when it will be ready ?

Thanks for all your job. Very usefull plugin.

JM

 

 

 

De : Thijs <notifications@github.com> 
Envoyé : jeudi 10 décembre 2020 16:41
À : thijsbekke/Octoprint-LaMetric <Octoprint-LaMetric@noreply.github.com>
Cc : jmarc67 <j-marc.67@wanadoo.fr>; Author <author@noreply.github.com>
Objet : Re: [thijsbekke/Octoprint-LaMetric] Not found error (#5)

 

Hi,

It are two different apps/plugins with different purposes.

The purpose of the OctoPrint app on your LaMetric is too display the number of installs of a plugin. In the settings of this app (in the LaMetric app) you can enter your a OctoPrint plugin name. If none is entered "X Not Found" is displayed (maybe that is a bit confusing ..)

Too display the progress of a print printed with OctoPrint no app on your LaMetric is required.

Hope this helps

Below a screenshot of the settings in de LaMetric app.
 <https://user-images.githubusercontent.com/1152678/101793551-3762da80-3b06-11eb-9248-0957900b9b0d.png>
