### ISSUE TITLE
OAuth endpoint gives error 500

### ISSUE THREAD

**Issue by deftdawg** [thijsbekke/Octoprint-LaMetric#8]
This endpoint (https://lametric.thedutchguys.com/oauth) that user's get redirected to after going to lametric's site gives an HTTP Error 500.

**Comment by thijsbekke** [comment]
Sorry, I will look into it later this day. 

Thanks for creating this issue.

**Comment by thijsbekke** [comment]
Hi, 

It works can you confirm that when you request an API key from OctoPrint you won't get an error? You don't have too do anything it was a server misconfiguration.

**Comment by deftdawg** [comment]
Yep working now, thanks
